version: '3.8'
services:
  app:
    build: .
    ports:
      - '5000:5000'
      - '443:443'
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    profiles:
      - dev
    command: npm run start:dev
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
